[nitpick]
minimum_version = "0.10.0"

[nitpick.files.present]
".bumpversion.cfg" = ""
".style.yapf" = ""
".tool-versions" = ""
".pre-commit-config.yaml" = ""
".gitownrc" = ""
"CHANGELOG.md" = ""
"README.md" = ""
"LICENSE" = ""

[nitpick.styles]
include = [
	"nitpick/editorconfig.toml",
	"nitpick/gitlint.toml",
	"nitpick/pylint.toml",
	"nitpick/package-json.toml",
	"nitpick/cmake.toml",
	"nitpick/github.toml",
	"nitpick/clang_format.toml",
	"nitpick/clang_tidy.toml"
]
