[nitpick]
minimum_version = "0.10.0"

[nitpick.files.present]
".editorconfig" = ""
".tool-versions" = ""
".pre-commit-config.yaml" = ""
".gitownrc" = ""
".pylintrc" = ""
".ecrc" = ""
".style.yapf" = ""
".gitlint" = ""
"CHANGELOG.md" = ""
"README.md" = ""
"LICENSE" = ""
"CMakeLists.txt" = ""

[".editorconfig"."*"]
insert_final_newline = true
trim_trailing_whitespace = true
indent_style = tab
indent_size = tab
tab_width = 4
end_of_line = lf
charset = utf-8
max_line_length = off

[".editorconfig"."*.md"]
trim_trailing_whitespace = false

[".editorconfig"."*.{yml,yaml,json}"]
ndent_style = space
indent_size = 2

[".editorconfig"."*.xml"]
indent_style = space
